/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moving.between.sourcesets.bug;

import other.sourceset.dude.Thing;

public class Library {
    public boolean someLibraryMethod() {
        new Thing().thing();
        return true;
    }
}
